appname: juxBar
logging:
  level:
    org:
      springframework:
        security: DEBUG
        cache: info

spring:
  application:
    name: juxBar
  cache:
    caffeine:
      spec: maximumSize=1500,expireAfterAccess=10m
  config:
    import: optional:classpath:/application-docker-configuration.yml
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://cocktaildb:3306/cocktailDB?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
