appname: juxBar
logging:
  level:
    org:
      springframework:
        security: DEBUG
        cache: info
server:
  address: 0.0.0.0
  port: 8443
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: yesyes
    key-store-type: PKCS12
    key-alias: juxbar
  compression:
    enabled: true
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript, application/javascript, application/json, image/jpeg, image/png
    min-response-size: 1024

spring:
  application:
    name: juxBar
  cache:
    caffeine:
      spec: maximumSize=1500,expireAfterAccess=10m
  config:
    import: optional:classpath:/application-docker-configuration.yml
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://cocktaildb:3306/cocktailDB?createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
